[package]
name = "touying-ufac"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["Lucas Lima Rodrigues <https://github.com/lucaslrodri>"]
license = "MIT"
description = "Touying Slide Theme for Federal University of Acre"
# homepage = "https://github.com/lucaslrodri/touying-ufac"
repository = "https://github.com/lucaslrodri/touying-ufac"
keywords = ["touying", "slide", "theme", "ufac", "university", "lecture", "acre"]
categories = ["presentation"]
compiler = "0.13"
exclude = [".github/", "examples/"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"